### ISSUE TITLE
problems parsing ccc_compiled.csv

### ISSUE THREAD

**Issue by MichaelMBishop** [nonviolent-action-lab/crowd-counting-consortium#2]
I'm getting problems parsing the csv, I don't have time to investigate much but wanted to let you know.

```
> prot <- read_csv("~/crowd-counting-consortium/ccc_compiled.csv")
Parsed with column specification:
cols(
  .default = col_character(),
  Date = col_date(format = ""),
  County = col_logical(),
  Online = col_double(),
  ClaimType = col_double(),
  EstimateLow = col_double(),
  EstimateHigh = col_double(),
  EstimateText = col_logical(),
  EstimateCat = col_double(),
  ReportedArrests = col_double(),
  ReportedParticipantInjuries = col_double(),
  ReportedPoliceInjuries = col_double(),
  ReportedPropertyDamage = col_double(),
  Final = col_double(),
  lat = col_double(),
  lon = col_double()
)
See spec(...) for full column specifications.
Warning: 41534 parsing failures.
 row          col           expected    actual                                           file
1237 EstimateText 1/0/T/F/TRUE/FALSE hundreds  '~/crowd-counting-consortium/ccc_compiled.csv'
1245 EstimateText 1/0/T/F/TRUE/FALSE dozens    '~/crowd-counting-consortium/ccc_compiled.csv'
1258 EstimateText 1/0/T/F/TRUE/FALSE thousands '~/crowd-counting-consortium/ccc_compiled.csv'
1259 EstimateText 1/0/T/F/TRUE/FALSE hundreds  '~/crowd-counting-consortium/ccc_compiled.csv'
1260 EstimateText 1/0/T/F/TRUE/FALSE na        '~/crowd-counting-consortium/ccc_compiled.csv'
.... ............ .................. ......... ..............................................
See problems(...) for more details.


> problems(prot)
# A tibble: 41,534 x 5
     row col         expected          actual        file                                   
   <int> <chr>       <chr>             <chr>         <chr>                                  
 1  1237 EstimateTe… 1/0/T/F/TRUE/FAL… hundreds      '~/crowd-counting-consortium/ccc_compi…
 2  1245 EstimateTe… 1/0/T/F/TRUE/FAL… dozens        '~/crowd-counting-consortium/ccc_compi…
 3  1258 EstimateTe… 1/0/T/F/TRUE/FAL… thousands     '~/crowd-counting-consortium/ccc_compi…
 4  1259 EstimateTe… 1/0/T/F/TRUE/FAL… hundreds      '~/crowd-counting-consortium/ccc_compi…
 5  1260 EstimateTe… 1/0/T/F/TRUE/FAL… na            '~/crowd-counting-consortium/ccc_compi…
 6  1261 EstimateTe… 1/0/T/F/TRUE/FAL… hundreds      '~/crowd-counting-consortium/ccc_compi…
 7  1262 EstimateTe… 1/0/T/F/TRUE/FAL… several hund… '~/crowd-counting-consortium/ccc_compi…
 8  1265 EstimateTe… 1/0/T/F/TRUE/FAL… nearly 300    '~/crowd-counting-consortium/ccc_compi…
 9  1266 EstimateTe… 1/0/T/F/TRUE/FAL… na            '~/crowd-counting-consortium/ccc_compi…
10  1267 EstimateTe… 1/0/T/F/TRUE/FAL… 650 or so     '~/crowd-counting-consortium/ccc_compi…
# … with 41,524 more rows
```

**Comment by nonviolent-action-lab** [comment]
This problem seems to be specific to the `read_csv()` function from `readr`. I can replicate your issue if I use it, but I have no problems if I use base R's `read.csv()` instead.

So, I think you've got two options here.

1. Use `read.csv()` instead, and then convert to a tibble from there if you like.
2. Use `read_csv()`, but specify `col_types` in the call to it.

The latter seems like a lot of unnecessary work to me, but I think that's the only way to get that column to read correctly from the current file.

**Comment by MichaelMBishop** [comment]
Apologies for my laziness, I thought I tried read.csv() but apparently I didn't!
And of course you should feel no obligation to address any minor issues I raise - take what value you can get from me and ignore the rest!

I might drop a few more comments on this issue.
I noticed this unusual end of line:
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/965005/91082045-0f627080-e616-11ea-81c5-34e3dd03d7e1.png"> b

Which my text editor called "Inconsistent double quotes"

And I see a similar issue at line 6881 in another field, and elsewhere.

**Comment by MichaelMBishop** [comment]
It is not clear to me if ^^ the source of the problem with read_csv(), but you might your pipeline to fix it regardless. R's str_trim( ..., side="both") run on all fields might fix it?

**Comment by nonviolent-action-lab** [comment]
Good catch, and good suggestion on `str_trim()`, thanks.

**Comment by nonviolent-action-lab** [comment]
I tried using `str_trim()` on all string columns after compiling, but I don't think it will have fixed the problem. There's something going on in the sheet for June 2020 that I think is causing this. I will keep investigating and hope to get it cleared up before next week's update.

**Comment by nonviolent-action-lab** [comment]
I think I found and fixed the main source of this problem, which was merged cells in one originating Google Sheet. If I run `read_csv()` now, I still get warnings for parsing failures, but they all stem from the function reading as logical a column that should be read as strings (`size_text`). And `read.csv()` still works fine. So I'm going to mark this one as closed and figure what's left is on `read_csv()` and not the data.

**Comment by MichaelMBishop** [comment]
Thanks so much Jay!

I can confirm, also, that data.table's `fread()` reads with no errors and sees that column as `character`.

Your time is too important to worry about this any more, but if you want to give an RA the job of looking into it more you could give them these notes. 

The column in question (in csv) contains a lot of `NA` . No quotes around the NA. An alternative would be simply leaving it blank so you'd see commas next to eachother:
 ,,  
another alternative would be using empty quotes, so the NA would look like:
,"",
