### ISSUE TITLE
capitalize column names for consistency?

### ISSUE THREAD

**Issue by MichaelMBishop** [nonviolent-action-lab/crowd-counting-consortium#3]
Best to have either none or all variable names capitalized.
 
```
lat. Latitude of locality in which the event took place, as resolved by Google Maps Geocoding API.

lon. Longitude of locality in which the event took place, as resolved by Google Maps Geocoding API.

locality. Name of the locality in which the event took place, as resolved by Google Maps Geocoding API.

county. Name of the county in which that locality sits, as resolved by the Google Maps Geocoding API.

state. Postal abbreviation of the state or territory in which that locality sits, as resolved by the Google Maps Geocoding API.
```

**Comment by nonviolent-action-lab** [comment]
I chose this approach to make it easier for people already familiar with the CCC data to find what they're looking for, and to differentiate the geolocation columns that were generally programmatically from the ones that weren't. As you point out, though, that's not best practice, so I will come up with a more coherent and "proper" syntax starting with the next update.

**Comment by nonviolent-action-lab** [comment]
Starting with this morning's update, the column names have all been changed to lowercase (and, in some cases, renamed). Where relevant, the data dictionary identifies the name of the column in the source data (i.e., the CCC Google Sheets) that matches the column in the compiled data.
